version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "next"
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    target-branch: "next"
    schedule:
      interval: daily